FROZEN_MANIFEST ?= boards/manifest.py
MICROPY_PY_NETWORK_IFX_WCM = 0
MICROPY_PY_NETWORK = 0
MICROPY_PSOC6_LWIP = 0
MICROPY_PY_SSL = 0
MICROPY_PSOC6_SSL_MBEDTLS = 0
MICROPY_PY_EXT_FLASH = 1
MICROPY_PY_SD_CARD = 0
MICROPY_VFS_FAT=0
BOARD_VERSION=release-v4.0.0

# Variables to support make-pins
PIN_PACKAGE_FILE = cyhal_psoc6_02_124_bga.h

# Flasher configuration
OPENOCD_TARGET_CFG=psoc6_2m.cfg