name: psoc6 port

on:
  push:
  pull_request:
    paths:
      - '.github/workflows/ports_psoc6.yml'
      - 'tools/**'
      - 'py/**'
      - 'extmod/**'
      - 'lib/**'
      - 'ports/psoc6/**'

jobs:
  server-build-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: source tools/ci.sh && ci_psoc6_setup
      - name: Build
        run: source tools/ci.sh && ci_psoc6_build
      - name: Save firmware bin
        if: success()
        uses: actions/upload-artifact@v3
        with: 
          name: Micropython PSoC6 Ports
          path: build/firmware.hex

  build-deploy-test:
    runs-on: self-hosted
    needs: server-build-check
    steps:
    - uses: actions/checkout@v2
    - name: Setup
      run : echo ${{ secrets.SELF_HOSTED_PASSWORD }} | sudo -S chmod 666 /var/run/docker.sock
    - name: Install packages
      run: source tools/ci.sh && ci_psoc6_setup --dev-access
    - name: Build
      run: source tools/ci.sh && ci_psoc6_build 
    - name: Deploy
      run: source tools/ci.sh && ci_psoc6_deploy
    - name: Run tests
      run : source tools/ci.sh && ci_psoc6_run_tests
    - name: Cleanup 
      if: success() || failure()
      run: |
        echo ${{ secrets.SELF_HOSTED_PASSWORD }} | sudo -S rm -rf ${GITHUB_WORKSPACE}
        mkdir ${GITHUB_WORKSPACE}
        docker stop mtb-ci
        docker system prune --all --force
