name: psoc6 port

on:
  push:
  pull_request:
    paths:
      - '.github/workflows/ports_psoc6.yml'
      - 'tools/**'
      - 'py/**'
      - 'extmod/**'
      - 'lib/**'
      - 'ports/psoc6/**'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, self-hosted]
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v2
    - name: Install packages
      run: source tools/ci.sh && ci_psoc6_setup
    - name: Build
      run: source tools/ci.sh && ci_psoc6_build
    - name: Deploy
      if: ${{matrix.os}} == 'self-hosted' && success()
      run: source tools/ci.sh && ci_psoc6_deploy
    - name: Run tests
      if: ${{matrix.os}} == 'self-hosted' && success()
      run : source tools/ci.sh && ci_psoc6_run_tests
    - name: Cleanup 
      if: ${{matrix.os}} == 'self-hosted' && (success() || failure())
      run: echo $PWD