name: psoc6 port

on:
  push:
  pull_request:
    paths:
      - '.github/workflows/ports_psoc6.yml'
      - 'tools/**'
      - 'py/**'
      - 'extmod/**'
      - 'lib/**'
      - 'ports/psoc6/**'

jobs:
  server-build-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: source tools/ci.sh && ci_psoc6_setup
      - name: Build
        run: source tools/ci.sh && ci_psoc6_build

  build-deploy-test:
    runs-on: self-hosted
    needs: server-build-check
    steps:
    - uses: actions/checkout@v2
    - name: Install packages
      run: source tools/ci.sh && ci_psoc6_setup --dev-access
    - name: Build
      run: source tools/ci.sh && ci_psoc6_build 
    - name: Deploy
      run: source tools/ci.sh && ci_psoc6_deploy
    - name: Run tests
      run : source tools/ci.sh && ci_psoc6_run_tests
    - name: Cleanup 
      if: success() || failure() # Cleanup despite the result
      run: echo $PWD