name: Sync Upstream

on:
  schedule:
    - cron: '*/1 * * * *' # every 1 minutes
  workflow_dispatch: # on button click


jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.6.3
        with:
          owner: micropython
          base: master
          head: ports/psoc6_ci-auto-synch
          merge_method: rebase